### ISSUE TITLE
Pubsub: Could not find a declaration file for module 'libp2p-pubsub'

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-interfaces#114]
Trying to update js-libp2p-gossipsub (tracking issue https://github.com/ChainSafe/js-libp2p-gossipsub/issues/171)

After installing `libp2p-pubsub` v0.7.0 and `libp2p-interfaces` v2.0.0
and adding this line:
```ts
import { PubsubBaseProtocol } from 'libp2p-pubsub'
```

I get the following error in my IDE:
```
Could not find a declaration file for module 'libp2p-pubsub'. '/home/cayman/Code/js-libp2p-gossipsub/node_modules/libp2p-pubsub/dist/src/index.js' implicitly has an 'any' type.
```

Also tried starting a new project and installing just those two packages, same error.

**Comment by achingbrain** [comment]
Could you try again please?  There was a bit of churn and I think you got caught up in it.

`libp2p-interfaces@2.x.x` was the [TypeScript refactor](https://github.com/libp2p/js-libp2p/issues/1021) but it became necessary to release that as `v3` since `libp2p-crypto` removed support for node 14 and below.

`libp2p-interfaces@1.x.x` then became `libp2p-interfaces@2.x.x` for the same reason.

`libp2p-pubsub` is not ready for use yet, it needs more of the ecosystem porting to TS - please stick with the PubSub base class defined in `libp2p-interfaces@2.x.x` for now.

Sorry for the disruption.

**Comment by lidel** [comment]
Closing as @wemeetagain say its no longer a problem :^)
