### ISSUE TITLE
Consider not running promises in forEach()

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p-interfaces#88]
`_processRpcMessage` is a promise and is run here inside a forEach.

https://github.com/libp2p/js-libp2p-interfaces/blob/b948972c5b8492b1edaf4946af79cc9834c8fc60/src/pubsub/index.js#L392-L399

Would it be better to run those in series instead of unhandled promises? Otherwise, would it make sense to run them at once with `Promise.all()` for better etiquette?

**Comment by vasco-santos** [comment]
Good point

We don't care about the message processing for the `_processRpcMessage`, so we don't need to block on that. 

However, we should definitely avoid the unhandled promise! At least wrap it with a try catch, otherwise it will go up in the stack and cause a disconnect, which might not be desirable. Regarding running the promise all in parallel and handling errors seems ideal to me.

@wemeetagain what do you think?

**Comment by dapplion** [comment]
> @wemeetagain what do you think?

He can reply latter himself, but we discovered this together yesterday and agrees that promises meant to run in parallel should be in a Promise.all()

**Comment by vasco-santos** [comment]
Awesome, can you submit a PR @dapplion ?

**Comment by wemeetagain** [comment]
This appears to be handled correctly now.
https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/libp2p-pubsub/src/index.ts#L309
